### ISSUE TITLE
Test failures using Python 3 on Debian Buster

### ISSUE THREAD

**Issue by sloretz** [ros-perception/image_common#137]
It looks there are a couple test failures with `camera_calibration_parsers` when using 
Python 3 on Debian Buster. These will need to be fixed for Noetic.

Full steps to reproduce are here: http://wiki.ros.org/UsingPython3/BuildUsingPython3

Built with
```
catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --catkin-make-args all tests
```

Ran tests with
```
catkin_make_isolated --force-cmake --catkin-make-args run_tests
```

Failed Test output
```
======================================================================
ERROR: test_readCalibration (parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sloretz/ic_ws/src/image_common/camera_calibration_parsers/test/parser.py", line 51, in test_readCalibration
    camera_name, camera_info = readCalibration(os.path.join(script_dir, 'calib5.ini'))
  File "<string>", line 12, in readCalibration
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 16: invalid continuation byte

======================================================================
FAIL: test_ini (parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sloretz/ic_ws/src/image_common/camera_calibration_parsers/test/parser.py", line 47, in test_ini
    self.assertEqual(err, '')
AssertionError: b'' != ''

----------------------------------------------------------------------
Ran 2 tests in 0.357s
```

<details><summary>Full output of `camera_calibration_parser`</summary>

```
==> Processing catkin package: camera_calibration_parsers
==> cmake /home/sloretz/ic_ws/src/image_common/camera_calibration_parsers -DCATKIN_DEVEL_PREFIX=/home/sloretz/ic_ws/devel_isolated/camera_calibration_parsers -DCMAKE_INSTALL_PREFIX=/home/sloretz/ic_ws/install_isolated -G Unix Makefiles in '/home/sloretz/ic_ws/build_isolated/camera_calibration_parsers'
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using CATKIN_DEVEL_PREFIX: /home/sloretz/ic_ws/devel_isolated/camera_calibration_parsers
-- Using CMAKE_PREFIX_PATH: /home/sloretz/ws/noetic/devel_isolated/kdl_parser_py;/home/sloretz/ws/noetic/devel_isolated/kdl_parser;/home/sloretz/ws/noetic/devel_isolated/urdf;/home/sloretz/ws/noetic/devel_isolated/tf_conversions;/home/sloretz/ws/noetic/devel_isolated/tf2_tools;/home/sloretz/ws/noetic/devel_isolated/tf2_sensor_msgs;/home/sloretz/ws/noetic/devel_isolated/test_tf2;/home/sloretz/ws/noetic/devel_isolated/tf2_kdl;/home/sloretz/ws/noetic/devel_isolated/tf2_geometry_msgs;/home/sloretz/ws/noetic/devel_isolated/laser_geometry;/home/sloretz/ws/noetic/devel_isolated/tf;/home/sloretz/ws/noetic/devel_isolated/tf2_ros;/home/sloretz/ws/noetic/devel_isolated/test_rostopic;/home/sloretz/ws/noetic/devel_isolated/test_rostest;/home/sloretz/ws/noetic/devel_isolated/test_rosservice;/home/sloretz/ws/noetic/devel_isolated/test_rospy;/home/sloretz/ws/noetic/devel_isolated/test_rosbag;/home/sloretz/ws/noetic/devel_isolated/test_nodelet_topic_tools;/home/sloretz/ws/noetic/devel_isolated/stereo_msgs;/home/sloretz/ws/noetic/devel_isolated/sensor_msgs;/home/sloretz/ws/noetic/devel_isolated/roswtf;/home/sloretz/ws/noetic/devel_isolated/nodelet_topic_tools;/home/sloretz/ws/noetic/devel_isolated/actionlib;/home/sloretz/ws/noetic/devel_isolated/rosbag;/home/sloretz/ws/noetic/devel_isolated/topic_tools;/home/sloretz/ws/noetic/devel_isolated/tf2_py;/home/sloretz/ws/noetic/devel_isolated/test_rosparam;/home/sloretz/ws/noetic/devel_isolated/test_rosmaster;/home/sloretz/ws/noetic/devel_isolated/test_roslaunch;/home/sloretz/ws/noetic/devel_isolated/test_rosgraph;/home/sloretz/ws/noetic/devel_isolated/test_roscpp;/home/sloretz/ws/noetic/devel_isolated/test_rosbag_storage;/home/sloretz/ws/noetic/devel_isolated/test_nodelet;/home/sloretz/ws/noetic/devel_isolated/test_bond;/home/sloretz/ws/noetic/devel_isolated/rqt_gui_py;/home/sloretz/ws/noetic/devel_isolated/rqt_gui_cpp;/home/sloretz/ws/noetic/devel_isolated/rostopic;/home/sloretz/ws/noetic/devel_isolated/rosnode;/home/sloretz/ws/noetic/devel_isolated/rosbag_storage;/home/sloretz/ws/noetic/devel_isolated/message_filters;/home/sloretz/ws/noetic/devel_isolated/filters;/home/sloretz/ws/noetic/devel_isolated/dynamic_reconfigure;/home/sloretz/ws/noetic/devel_isolated/rosout;/home/sloretz/ws/noetic/devel_isolated/nodelet;/home/sloretz/ws/noetic/devel_isolated/bondpy;/home/sloretz/ws/noetic/devel_isolated/bondcpp;/home/sloretz/ws/noetic/devel_isolated/roscpp;/home/sloretz/ws/noetic/devel_isolated/xmlrpcpp;/home/sloretz/ws/noetic/devel_isolated/webkit_dependency;/home/sloretz/ws/noetic/devel_isolated/visualization_msgs;/home/sloretz/ws/noetic/devel_isolated/urdfdom_py;/home/sloretz/ws/noetic/devel_isolated/urdf_parser_plugin;/home/sloretz/ws/noetic/devel_isolated/trajectory_msgs;/home/sloretz/ws/noetic/devel_isolated/tf2_eigen;/home/sloretz/ws/noetic/devel_isolated/tf2_bullet;/home/sloretz/ws/noetic/devel_isolated/tf2;/home/sloretz/ws/noetic/devel_isolated/tf2_msgs;/home/sloretz/ws/noetic/devel_isolated/test_roslib_comm;/home/sloretz/ws/noetic/devel_isolated/std_srvs;/home/sloretz/ws/noetic/devel_isolated/shape_msgs;/home/sloretz/ws/noetic/devel_isolated/rqt_py_common;/home/sloretz/ws/noetic/devel_isolated/rosmsg;/home/sloretz/ws/noetic/devel_isolated/rosgraph_msgs;/home/sloretz/ws/noetic/devel_isolated/nav_msgs;/home/sloretz/ws/noetic/devel_isolated/kdl_conversions;/home/sloretz/ws/noetic/devel_isolated/eigen_conversions;/home/sloretz/ws/noetic/devel_isolated/geometry_msgs;/home/sloretz/ws/noetic/devel_isolated/diagnostic_msgs;/home/sloretz/ws/noetic/devel_isolated/bond;/home/sloretz/ws/noetic/devel_isolated/actionlib_msgs;/home/sloretz/ws/noetic/devel_isolated/std_msgs;/home/sloretz/ws/noetic/devel_isolated/smclib;/home/sloretz/ws/noetic/devel_isolated/rqt_gui;/home/sloretz/ws/noetic/devel_isolated/rqt;/home/sloretz/ws/noetic/devel_isolated/rostest;/home/sloretz/ws/noetic/devel_isolated/roslz4;/home/sloretz/ws/noetic/devel_isolated/rosconsole_bridge;/home/sloretz/ws/noetic/devel_isolated/resource_retriever;/home/sloretz/ws/noetic/devel_isolated/qt_gui_cpp;/home/sloretz/ws/noetic/devel_isolated/pluginlib;/home/sloretz/ws/noetic/devel_isolated/rosconsole;/home/sloretz/ws/noetic/devel_isolated/angles;/home/sloretz/ws/noetic/devel_isolated/rosunit;/home/sloretz/ws/noetic/devel_isolated/roslaunch;/home/sloretz/ws/noetic/devel_isolated/python_qt_binding;/home/sloretz/ws/noetic/devel_isolated/roscpp_serialization;/home/sloretz/ws/noetic/devel_isolated/rostime;/home/sloretz/ws/noetic/devel_isolated/rosservice;/home/sloretz/ws/noetic/devel_isolated/rospy;/home/sloretz/ws/noetic/devel_isolated/rosparam;/home/sloretz/ws/noetic/devel_isolated/roslib;/home/sloretz/ws/noetic/devel_isolated/rospack;/home/sloretz/ws/noetic/devel_isolated/rosmaster;/home/sloretz/ws/noetic/devel_isolated/rosmake;/home/sloretz/ws/noetic/devel_isolated/roslisp;/home/sloretz/ws/noetic/devel_isolated/roslang;/home/sloretz/ws/noetic/devel_isolated/rosgraph;/home/sloretz/ws/noetic/devel_isolated/roscreate;/home/sloretz/ws/noetic/devel_isolated/roscpp_traits;/home/sloretz/ws/noetic/devel_isolated/roscpp_core;/home/sloretz/ws/noetic/devel_isolated/rosclean;/home/sloretz/ws/noetic/devel_isolated/rosbuild;/home/sloretz/ws/noetic/devel_isolated/rosboost_cfg;/home/sloretz/ws/noetic/devel_isolated/rosbash;/home/sloretz/ws/noetic/devel_isolated/rosbag_migration_rule;/home/sloretz/ws/noetic/devel_isolated/py3_example;/home/sloretz/ws/noetic/devel_isolated/python2or3;/home/sloretz/ws/noetic/devel_isolated/ros_environment;/home/sloretz/ws/noetic/devel_isolated/ros_comm;/home/sloretz/ws/noetic/devel_isolated/ros;/home/sloretz/ws/noetic/devel_isolated/random_numbers;/home/sloretz/ws/noetic/devel_isolated/qwt_dependency;/home/sloretz/ws/noetic/devel_isolated/qt_gui_py_common;/home/sloretz/ws/noetic/devel_isolated/qt_gui_core;/home/sloretz/ws/noetic/devel_isolated/qt_gui_app;/home/sloretz/ws/noetic/devel_isolated/qt_gui;/home/sloretz/ws/noetic/devel_isolated/qt_dotgraph;/home/sloretz/ws/noetic/devel_isolated/python_orocos_kdl;/home/sloretz/ws/noetic/devel_isolated/orocos_kinematics_dynamics;/home/sloretz/ws/noetic/devel_isolated/orocos_kdl;/home/sloretz/ws/noetic/devel_isolated/nodelet_core;/home/sloretz/ws/noetic/devel_isolated/mk;/home/sloretz/ws/noetic/devel_isolated/message_runtime;/home/sloretz/ws/noetic/devel_isolated/message_generation;/home/sloretz/ws/noetic/devel_isolated/gl_dependency;/home/sloretz/ws/noetic/devel_isolated/geometry2;/home/sloretz/ws/noetic/devel_isolated/geometry;/home/sloretz/ws/noetic/devel_isolated/eigen_stl_containers;/home/sloretz/ws/noetic/devel_isolated/cpp_common;/home/sloretz/ws/noetic/devel_isolated/common_msgs;/home/sloretz/ws/noetic/devel_isolated/class_loader;/home/sloretz/ws/noetic/devel_isolated/cmake_modules;/home/sloretz/ws/noetic/devel_isolated/bond_core;/home/sloretz/ws/noetic/devel_isolated/actionlib_tools;/home/sloretz/ws/noetic/devel_isolated/genpy;/home/sloretz/ws/noetic/devel_isolated/gennodejs;/home/sloretz/ws/noetic/devel_isolated/genlisp;/home/sloretz/ws/noetic/devel_isolated/geneus;/home/sloretz/ws/noetic/devel_isolated/gencpp;/home/sloretz/ws/noetic/devel_isolated/genmsg;/home/sloretz/ws/noetic/devel_isolated/catkin
-- This workspace overlays: /home/sloretz/ws/noetic/devel_isolated/kdl_parser_py;/home/sloretz/ws/noetic/devel_isolated/kdl_parser;/home/sloretz/ws/noetic/devel_isolated/urdf;/home/sloretz/ws/noetic/devel_isolated/tf_conversions;/home/sloretz/ws/noetic/devel_isolated/tf2_tools;/home/sloretz/ws/noetic/devel_isolated/tf2_sensor_msgs;/home/sloretz/ws/noetic/devel_isolated/test_tf2;/home/sloretz/ws/noetic/devel_isolated/tf2_kdl;/home/sloretz/ws/noetic/devel_isolated/tf2_geometry_msgs;/home/sloretz/ws/noetic/devel_isolated/laser_geometry;/home/sloretz/ws/noetic/devel_isolated/tf;/home/sloretz/ws/noetic/devel_isolated/tf2_ros;/home/sloretz/ws/noetic/devel_isolated/test_rostopic;/home/sloretz/ws/noetic/devel_isolated/test_rostest;/home/sloretz/ws/noetic/devel_isolated/test_rosservice;/home/sloretz/ws/noetic/devel_isolated/test_rospy;/home/sloretz/ws/noetic/devel_isolated/test_rosbag;/home/sloretz/ws/noetic/devel_isolated/test_nodelet_topic_tools;/home/sloretz/ws/noetic/devel_isolated/stereo_msgs;/home/sloretz/ws/noetic/devel_isolated/sensor_msgs;/home/sloretz/ws/noetic/devel_isolated/roswtf;/home/sloretz/ws/noetic/devel_isolated/nodelet_topic_tools;/home/sloretz/ws/noetic/devel_isolated/actionlib;/home/sloretz/ws/noetic/devel_isolated/rosbag;/home/sloretz/ws/noetic/devel_isolated/topic_tools;/home/sloretz/ws/noetic/devel_isolated/tf2_py;/home/sloretz/ws/noetic/devel_isolated/test_rosparam;/home/sloretz/ws/noetic/devel_isolated/test_rosmaster;/home/sloretz/ws/noetic/devel_isolated/test_roslaunch;/home/sloretz/ws/noetic/devel_isolated/test_rosgraph;/home/sloretz/ws/noetic/devel_isolated/test_roscpp;/home/sloretz/ws/noetic/devel_isolated/test_rosbag_storage;/home/sloretz/ws/noetic/devel_isolated/test_nodelet;/home/sloretz/ws/noetic/devel_isolated/test_bond;/home/sloretz/ws/noetic/devel_isolated/rqt_gui_py;/home/sloretz/ws/noetic/devel_isolated/rqt_gui_cpp;/home/sloretz/ws/noetic/devel_isolated/rostopic;/home/sloretz/ws/noetic/devel_isolated/rosnode;/home/sloretz/ws/noetic/devel_isolated/rosbag_storage;/home/sloretz/ws/noetic/devel_isolated/message_filters;/home/sloretz/ws/noetic/devel_isolated/filters;/home/sloretz/ws/noetic/devel_isolated/dynamic_reconfigure;/home/sloretz/ws/noetic/devel_isolated/rosout;/home/sloretz/ws/noetic/devel_isolated/nodelet;/home/sloretz/ws/noetic/devel_isolated/bondpy;/home/sloretz/ws/noetic/devel_isolated/bondcpp;/home/sloretz/ws/noetic/devel_isolated/roscpp;/home/sloretz/ws/noetic/devel_isolated/xmlrpcpp;/home/sloretz/ws/noetic/devel_isolated/webkit_dependency;/home/sloretz/ws/noetic/devel_isolated/visualization_msgs;/home/sloretz/ws/noetic/devel_isolated/urdfdom_py;/home/sloretz/ws/noetic/devel_isolated/urdf_parser_plugin;/home/sloretz/ws/noetic/devel_isolated/trajectory_msgs;/home/sloretz/ws/noetic/devel_isolated/tf2_eigen;/home/sloretz/ws/noetic/devel_isolated/tf2_bullet;/home/sloretz/ws/noetic/devel_isolated/tf2;/home/sloretz/ws/noetic/devel_isolated/tf2_msgs;/home/sloretz/ws/noetic/devel_isolated/test_roslib_comm;/home/sloretz/ws/noetic/devel_isolated/std_srvs;/home/sloretz/ws/noetic/devel_isolated/shape_msgs;/home/sloretz/ws/noetic/devel_isolated/rqt_py_common;/home/sloretz/ws/noetic/devel_isolated/rosmsg;/home/sloretz/ws/noetic/devel_isolated/rosgraph_msgs;/home/sloretz/ws/noetic/devel_isolated/nav_msgs;/home/sloretz/ws/noetic/devel_isolated/kdl_conversions;/home/sloretz/ws/noetic/devel_isolated/eigen_conversions;/home/sloretz/ws/noetic/devel_isolated/geometry_msgs;/home/sloretz/ws/noetic/devel_isolated/diagnostic_msgs;/home/sloretz/ws/noetic/devel_isolated/bond;/home/sloretz/ws/noetic/devel_isolated/actionlib_msgs;/home/sloretz/ws/noetic/devel_isolated/std_msgs;/home/sloretz/ws/noetic/devel_isolated/smclib;/home/sloretz/ws/noetic/devel_isolated/rqt_gui;/home/sloretz/ws/noetic/devel_isolated/rqt;/home/sloretz/ws/noetic/devel_isolated/rostest;/home/sloretz/ws/noetic/devel_isolated/roslz4;/home/sloretz/ws/noetic/devel_isolated/rosconsole_bridge;/home/sloretz/ws/noetic/devel_isolated/resource_retriever;/home/sloretz/ws/noetic/devel_isolated/qt_gui_cpp;/home/sloretz/ws/noetic/devel_isolated/pluginlib;/home/sloretz/ws/noetic/devel_isolated/rosconsole;/home/sloretz/ws/noetic/devel_isolated/angles;/home/sloretz/ws/noetic/devel_isolated/rosunit;/home/sloretz/ws/noetic/devel_isolated/roslaunch;/home/sloretz/ws/noetic/devel_isolated/python_qt_binding;/home/sloretz/ws/noetic/devel_isolated/roscpp_serialization;/home/sloretz/ws/noetic/devel_isolated/rostime;/home/sloretz/ws/noetic/devel_isolated/rosservice;/home/sloretz/ws/noetic/devel_isolated/rospy;/home/sloretz/ws/noetic/devel_isolated/rosparam;/home/sloretz/ws/noetic/devel_isolated/roslib;/home/sloretz/ws/noetic/devel_isolated/rospack;/home/sloretz/ws/noetic/devel_isolated/rosmaster;/home/sloretz/ws/noetic/devel_isolated/rosmake;/home/sloretz/ws/noetic/devel_isolated/roslisp;/home/sloretz/ws/noetic/devel_isolated/roslang;/home/sloretz/ws/noetic/devel_isolated/rosgraph;/home/sloretz/ws/noetic/devel_isolated/roscreate;/home/sloretz/ws/noetic/devel_isolated/roscpp_traits;/home/sloretz/ws/noetic/devel_isolated/roscpp_core;/home/sloretz/ws/noetic/devel_isolated/rosclean;/home/sloretz/ws/noetic/devel_isolated/rosbuild;/home/sloretz/ws/noetic/devel_isolated/rosboost_cfg;/home/sloretz/ws/noetic/devel_isolated/rosbash;/home/sloretz/ws/noetic/devel_isolated/rosbag_migration_rule;/home/sloretz/ws/noetic/devel_isolated/py3_example;/home/sloretz/ws/noetic/devel_isolated/python2or3;/home/sloretz/ws/noetic/devel_isolated/ros_environment;/home/sloretz/ws/noetic/devel_isolated/ros_comm;/home/sloretz/ws/noetic/devel_isolated/ros;/home/sloretz/ws/noetic/devel_isolated/random_numbers;/home/sloretz/ws/noetic/devel_isolated/qwt_dependency;/home/sloretz/ws/noetic/devel_isolated/qt_gui_py_common;/home/sloretz/ws/noetic/devel_isolated/qt_gui_core;/home/sloretz/ws/noetic/devel_isolated/qt_gui_app;/home/sloretz/ws/noetic/devel_isolated/qt_gui;/home/sloretz/ws/noetic/devel_isolated/qt_dotgraph;/home/sloretz/ws/noetic/devel_isolated/python_orocos_kdl;/home/sloretz/ws/noetic/devel_isolated/orocos_kinematics_dynamics;/home/sloretz/ws/noetic/devel_isolated/nodelet_core;/home/sloretz/ws/noetic/devel_isolated/mk;/home/sloretz/ws/noetic/devel_isolated/message_runtime;/home/sloretz/ws/noetic/devel_isolated/message_generation;/home/sloretz/ws/noetic/devel_isolated/gl_dependency;/home/sloretz/ws/noetic/devel_isolated/geometry2;/home/sloretz/ws/noetic/devel_isolated/geometry;/home/sloretz/ws/noetic/devel_isolated/eigen_stl_containers;/home/sloretz/ws/noetic/devel_isolated/cpp_common;/home/sloretz/ws/noetic/devel_isolated/common_msgs;/home/sloretz/ws/noetic/devel_isolated/class_loader;/home/sloretz/ws/noetic/devel_isolated/cmake_modules;/home/sloretz/ws/noetic/devel_isolated/bond_core;/home/sloretz/ws/noetic/devel_isolated/actionlib_tools;/home/sloretz/ws/noetic/devel_isolated/genpy;/home/sloretz/ws/noetic/devel_isolated/gennodejs;/home/sloretz/ws/noetic/devel_isolated/genlisp;/home/sloretz/ws/noetic/devel_isolated/geneus;/home/sloretz/ws/noetic/devel_isolated/gencpp;/home/sloretz/ws/noetic/devel_isolated/genmsg;/home/sloretz/ws/noetic/devel_isolated/catkin
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.3", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/sloretz/ic_ws/build_isolated/camera_calibration_parsers/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.7.3") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.7.19
-- BUILD_SHARED_LIBS is on
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   filesystem
--   python3
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sloretz/ic_ws/build_isolated/camera_calibration_parsers
==> make run_tests -j8 -l8 in '/home/sloretz/ic_ws/build_isolated/camera_calibration_parsers'
Scanning dependencies of target clean_test_results_camera_calibration_parsers
Built target tests
Removing test result files from '/home/sloretz/ic_ws/build_isolated/camera_calibration_parsers/test_results/camera_calibration_parsers'
Built target clean_test_results_camera_calibration_parsers
Scanning dependencies of target _run_tests_camera_calibration_parsers_nosetests_parser.py
-- run_tests.py: execute commands
  "/usr/bin/cmake" -E make_directory /home/sloretz/ic_ws/build_isolated/camera_calibration_parsers/test_results/camera_calibration_parsers
  /usr/bin/nosetests3 -P --process-timeout=60 /home/sloretz/ic_ws/src/image_common/camera_calibration_parsers/test/parser.py --with-xunit --xunit-file=/home/sloretz/ic_ws/build_isolated/camera_calibration_parsers/test_results/camera_calibration_parsers/nosetests-parser.py.xml
[ INFO] [1571181516.292756727]: Saved calib5.yaml
FE
======================================================================
ERROR: test_readCalibration (parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sloretz/ic_ws/src/image_common/camera_calibration_parsers/test/parser.py", line 51, in test_readCalibration
    camera_name, camera_info = readCalibration(os.path.join(script_dir, 'calib5.ini'))
  File "<string>", line 12, in readCalibration
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 16: invalid continuation byte

======================================================================
FAIL: test_ini (parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sloretz/ic_ws/src/image_common/camera_calibration_parsers/test/parser.py", line 47, in test_ini
    self.assertEqual(err, '')
AssertionError: b'' != ''

----------------------------------------------------------------------
Ran 2 tests in 0.357s

FAILED (errors=1, failures=1)
-- run_tests.py: verify result "/home/sloretz/ic_ws/build_isolated/camera_calibration_parsers/test_results/camera_calibration_parsers/nosetests-parser.py.xml"
Built target _run_tests_camera_calibration_parsers_nosetests_parser.py
Scanning dependencies of target _run_tests_camera_calibration_parsers_nosetests
Built target _run_tests_camera_calibration_parsers_nosetests
Scanning dependencies of target _run_tests_camera_calibration_parsers
Built target _run_tests_camera_calibration_parsers
Scanning dependencies of target run_tests
Built target run_tests
<== Finished processing package [1 of 5]: 'camera_calibration_parsers'

```
</details>

**Comment by sloretz** [comment]
I think this was fixed by https://github.com/ros-perception/image_common/pull/155 , closing.
